[package]
name = "axum-htmx-derive"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
proc-macro-error = "1.0"
proc-macro2 = "1.0"
quote = "1.0"
syn = { version = "1.0", features = ["extra-traits", "full", "fold"] }

[dev-dependencies]
colored-diff = "0.2.3"
